name: Production Deployment

on:
  push:
    branches:
      - "releases/**"

jobs:
  migrate-dbs:
    name: Deploy Database Schema
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: ./.github/actions/production-wrangler
        with:
          dashboard_database_id: ${{ secrets.DASHBOARD_D1_DATABASE_ID }}
          sensor_database_id: ${{ secrets.SENSOR_D1_DATABASE_ID }}

      - name: Push database schema
        run: pnpm d1:migrate
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: migrate-dbs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: ./.github/actions/production-wrangler
        with:
          dashboard_database_id: ${{ secrets.DASHBOARD_D1_DATABASE_ID }}
          sensor_database_id: ${{ secrets.SENSOR_D1_DATABASE_ID }}

      - name: Build & Deploy Worker
        working-directory: "apps/api"
        run: pnpm cf:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-reviewer:
    name: Deploy Reviewer Scheduler
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: migrate-dbs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: ./.github/actions/production-wrangler
        with:
          dashboard_database_id: ${{ secrets.DASHBOARD_D1_DATABASE_ID }}
          sensor_database_id: ${{ secrets.SENSOR_D1_DATABASE_ID }}

      - name: Build & Deploy Worker
        working-directory: "apps/reviewer"
        run: pnpm cf:deploy:daily
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-sensor-ingest:
    name: Deploy Sensor Ingest
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: migrate-dbs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: ./.github/actions/production-wrangler
        with:
          dashboard_database_id: ${{ secrets.DASHBOARD_D1_DATABASE_ID }}
          sensor_database_id: ${{ secrets.SENSOR_D1_DATABASE_ID }}

      - name: Build & Deploy Worker
        working-directory: "apps/sensor-ingest"
        run: pnpm cf:deploy:producer
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Build & Deploy Worker
        working-directory: "apps/sensor-ingest"
        run: pnpm cf:deploy:consumer
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-dashboard:
    name: Deploy Dashboard
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: deploy-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: ./.github/actions/production-wrangler
        with:
          dashboard_database_id: ${{ secrets.DASHBOARD_D1_DATABASE_ID }}
          sensor_database_id: ${{ secrets.SENSOR_D1_DATABASE_ID }}

      - name: Build & Deploy Worker
        working-directory: "apps/dashboard"
        run:  pnpm cf:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NEXT_PUBLIC_API_URL: ${{ secrets.DASHBOARD_API_URL }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.DASHBOARD_SITE_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
